### PR TITLE
Suppress unpacking output

### PR DESCRIPTION
**Pull request by musm**
close https://github.com/JuliaLang/BinDeps.jl/issues/274

### CODE REVIEW

**Comment by tkelman** [comment]
I don't think this should unconditionally silence all output, you do still want to see if something unexpected happens. The unix unpackers should mostly be well behaved about what they send to stdout vs stderr, but 7z isn't.

**Comment by musm** [comment]
it will still report errors and I think that's the only important thing from a user stand point. The 7z change on windows at least fixes the annoying issue for me.

If you want I can get rid of the other changed on non windows systems

**Comment by tkelman** [comment]
If you get a corrupted download, you want to see the error.

**Comment by musm** [comment]
what I have right will throw errors, e.g.
```julia

julia> run(pipeline(`7z df.s`, stdout=DevNull))
ERROR: failed process: Process(`7z df.s`, ProcessExited(7)) [7]
Stacktrace:
 [1] pipeline_error(::Base.Process) at .\process.jl:687
 [2] run(::Base.CmdRedirect) at .\process.jl:656

# C.F.

julia> run(pipeline(`7z df.s`, stdout=STDOUT))

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18


Error:
Incorrect command line
ERROR: failed process: Process(`7z df.s`, ProcessExited(7)) [7]
Stacktrace:
 [1] pipeline_error(::Base.Process) at .\process.jl:687
 [2] run(::Base.CmdRedirect) at .\process.jl:656

```

**Comment by tkelman** [comment]
"Incorrect command line" is the important part of that to see what was wrong.

**Comment by musm** [comment]
I can regex capture the error instead

**Comment by tkelman** [comment]
if there's a way of asking for a file list, would be better to filter that out since that's the majority of the issue here

**Comment by musm** [comment]
Searching the web, there does not seem to be such an option. All the recommended options are to search for "evertyhing is ok" and "error"

**Comment by tkelman** [comment]
or look at the exit code, as winrpm does

or convince the 7zip developer to add a quiet flag

**Comment by musm** [comment]
Ok thanks, I'm going to close this and leave the issue open for a better solution.

**Pull request closed without merging**
