### PR TITLE
Grab bag of fixes for 0.7

### PR DESCRIPTION
**Pull request by ararslan**
@amellnik Can you confirm that this fixes the issue you were seeing with ZMQ on Windows?

Fixes https://github.com/JuliaMath/SpecialFunctions.jl/issues/64
Fixes https://github.com/JuliaMath/FFTW.jl/issues/48

### CODE REVIEW

**Comment by amellnik** [comment]
I'm getting a different error now from [this line](https://github.com/JuliaInterop/ZMQ.jl/blob/master/deps/build.jl#L19) that looks like it's also BinDeps related.  The full stacktrace is:

```
ERROR: LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type Symbol
This may have arisen from a call to the constructor Symbol(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] setindex!(::Dict{Symbol,Any}, ::Tuple{Symbol,Array{String,1}}, ::Int64) at .\dict.jl:414
 [2] Dict{Symbol,Any}(::Array{Pair{Int64,Any},1}) at .\dict.jl:114
 [3] #_library_dependency#23(::Array{Any,1}, ::Function, ::BinDeps.PackageContext, ::String) at C:\Users\Alex\.julia\v0.7\BinDeps\src\dependencies.jl:65
 [4] (::getfield(BinDeps, Symbol("#kw##_library_dependency")))(::Array{Any,1}, ::typeof(BinDeps._library_dependency), ::BinDeps.PackageContext, ::String) at .\<missing>:0
 [5] #library_dependency#1(::Array{Any,1}, ::Function, ::String, ::Vararg{String,N} where N) at C:\Users\Alex\.julia\v0.7\BinDeps\src\dependencies.jl:91
 [6] (::getfield(, Symbol("#kw##library_dependency")))(::Array{Any,1}, ::typeof(library_dependency), ::String, ::Vararg{String,N} where N) at .\<missing>:0
 [7] top-level scope
 [8] include_relative(::Module, ::String) at .\loading.jl:509
 [9] include(::Module, ::String) at .\sysimg.jl:15
 [10] include(::String) at .\sysimg.jl:54
 [11] top-level scope
in expression starting at C:\Users\Alex\.julia\v0.7\ZMQ\deps\build.jl:19
```

(For anyone who's wondering, my original issue was here: https://github.com/JuliaInterop/ZMQ.jl/issues/159#issuecomment-347591540)

**Comment by ararslan** [comment]
Okay, well the first commit here that's supposed to fix the command line syntax is just flat out wrong. I need to find a way to work around how Julia does quoting in command literals.

The second commit seems to be causing the conversion errors, but I'm not sure why yet. I think it might be calling `pairs` on a vector of pairs, which gives you (essentially) e.g. `[1 => (:a=>x), 2 => (:b=>y)]`.

**Comment by ararslan** [comment]
The adjusted command syntax seems to be similarly incorrect.

**Comment by ararslan** [comment]
@amellnik When you're around next can you try forcibly resetting your local checkout of this branch and trying again?
```julia
cd(Pkg.dir("BinDeps")) do
    run(`git fetch origin --prune`)
    run(`git checkout aa/0.7`) # Just in case
    run(`git reset --hard origin/aa/0.7`)
end
Pkg.build("ZMQ")
```

**Comment by amellnik** [comment]
Using a new nightly and `aa/0.7` as described above I'm still seeing this.  I also restarted without starting jupyter as per @tkelman .    However, looking at this more I think the file names are off:

```
LoadError: failed process: Process(`'C:\Users\amellnik\AppData\Local\Julia-0.7.0-DEV\bin\7z.exe' x 
  -y 'C:\Users\amellnik\.julia\v0.7\WinRPM\cache\2\noarch%2Fmingw64-libwinpthread1-5.0.3-
  1.2.noarch.cpio' '-oC:\Users\amellnik\.julia\v0.7\WinRPM\deps'`, ProcessExited(2)) [2]
in expression starting at C:\Users\amellnik\.julia\v0.7\ZMQ\deps\build.jl:975
```

There's a file with that name but a `.rpm` extension, and a differently-named file with a `.cpio` extension.  I thought I checked the file it was targeting previously but I may have missed it having the wrong extension -- sorry.

**Comment by tkelman** [comment]
It's possible this was a behavior change with the bundled version of 7zip between julia 0.6 and 0.7.

**Comment by amellnik** [comment]
I think it's just a file extension issue -- the exact same command that is causing the error above works if you change the extension from `.cpio` to `.rpm`.

**Comment by tkelman** [comment]
No, there are both. The rpm contains the cpio, the cpio contains the dlls.

**Comment by tkelman** [comment]
The calls to 7zip in question here are also entirely contained within the WinRPM code, not done by BinDeps

**Comment by amellnik** [comment]
Tony is correct, and I commented with some findings in https://github.com/JuliaPackaging/WinRPM.jl/issues/134.

**Comment by ararslan** [comment]
The CI failures here are unrelated. The 0.7 Linux failures are the fault of URIParser and that will be fixed with the next URIParser tag. 0.6 Windows 32-bit seems like an AppVeyor network failure, and the 0.7 Windows failures are from WinRPM.

**Pull request merged**
