### PR TITLE
fix depwarns under 0.7 and bump REQUIRE and CI to 0.6

### PR DESCRIPTION
**Pull request by Sacha0**
Best! :)

### CODE REVIEW

**Comment by ararslan** [comment]
See #314

**Comment by Sacha0** [comment]
Thanks for the link! I checked only open pull requests :).

**Comment by musm** [comment]
See also https://github.com/JuliaLang/BinDeps.jl/pull/285/files
`take!` should be taken out when 0.5 is dropped as well

**Comment by ararslan** [comment]
Superseded by #336.

**Pull request closed without merging**
