### PR TITLE
Revert "Allow providing multiple package names as vector in provides()"

### PR DESCRIPTION
**Pull request by tkelman**
This broke WinRPM, ref https://github.com/JuliaLang/Cairo.jl/issues/132

### CODE REVIEW

**Comment by tkelman** [comment]
One of the Travis nightly jobs hit a `The command "curl -s -L -o julia.dmg 'https://s3.amazonaws.com/julianightlies/bin/osx/x64/julia-latest-osx.dmg'" failed and exited with 18 during .`, restarted.

**Comment by nalimilan** [comment]
I don't understand why this fails, but a possible workaround would be to add this to WinRPM:
```julia
function provides(::Type{RPM}, packages::AbstractArray, dep::LibraryDependency; opts...) = provides(provider(RPM, p; opts...), dep; opts...)
```

This would effectively revert this change only for WinRPM, which is the only provider to support passing multiple packages on its own (i.e. even without my PR). Then we could look for a long-term fix. Could you check whether it works?

**Comment by tkelman** [comment]
Will try that.

**Comment by tkelman** [comment]
Yep, that works, good call.

**Comment by nalimilan** [comment]
Cool, but we should investigate why this doesn't work.

**Comment by tkelman** [comment]
Agreed.

**Pull request closed without merging**
