### PR TITLE
String -> AbstractString

### PR DESCRIPTION
**Pull request by yuyichao**
Fix deprecation warnings...

### CODE REVIEW

**Comment by yuyichao** [comment]
May require https://github.com/JuliaLang/Compat.jl/pull/139 for 0.3.

**Comment by tkelman** [comment]
I'm guesing coverage is probably pretty bad here. What code paths might hit the `lower(s::Void,collection)` method? If that relies on a not-yet-tagged version of Compat then it'll have to wait for that version to be tagged and reflected in REQUIRE here.

Want to be careful not to break 0.3 of course.

**Comment by yuyichao** [comment]
Bump Compat requirement to 0.7.1 .

Not sure what's the best way to trigger `lower(s::Void, collection)`. I added a `@test BinDeps.lower(nothing, nothing) === nothing` in the test. Someone more familiar with this could probably come up with better test than this....

**Comment by yuyichao** [comment]
@tkelman Can I take your https://github.com/JuliaLang/julia/pull/13107#issuecomment-140935688 as this PR has been tested? =)

**Comment by tkelman** [comment]
Briefly, but only on 0.4. I trust if this breaks anything on 0.3 you'll be available to fix it.

**Comment by yuyichao** [comment]
> I trust if this breaks anything on 0.3 you'll be available to fix it.

Fine. I'll keep an eye on it while I'm figuring out how to get PkgEval working.

**Pull request merged**
