### PR TITLE
Fix depwarn on 0.5 about symbol and ASCIIString

### PR DESCRIPTION
**Pull request by yuyichao**
Requires a new tag of Compat.jl for `symbol`. I'm not sure if there's a better way to handle `ASCIIString` since there's apparently other packages that depend on this type (it's used in `Conda` for example).

### CODE REVIEW

**Comment by nalimilan** [comment]
Couldn't you add a type parameter `T<:AbstractString` instead? I don't think we care about the exact type of the string. Same for most cases where `ASCIIString` or `ByteString` appear.

**Comment by yuyichao** [comment]
Whether that is doable depend on the exact/expected usage. Given the low test coverage of this package and the span of supported versions I'd like to change as little as possible on old versions.

**Comment by nalimilan** [comment]
Really, I don't think it could cause any issue. All package names are ASCII, so in practice on 0.4 the field will always end up `ASCIIString`.

**Comment by yuyichao** [comment]
Closed in favor of #217

**Pull request closed without merging**
