### PR TITLE
add PathRule for use in FileUnpacker

### PR DESCRIPTION
**Pull request by kbarbary**
This adds a new type `PathRule` for the benefit of `FileUnpacker`. When unpacking an archive, we specify a target that should be created after the file is unpacked. Before #153, that target had to be a directory. For archives that don't contain any directories, we would like to specify a target *file* that should be created. Using `PathRule` instead of `DirectoryRule` or `FileRule` makes it so that the target can be either: it's existence is tested with `ispath` rather than `isdir` or `isfile`.

Hopefully this will fix regressions caused by #153, such as #157.

### CODE REVIEW

**Comment by tkelman** [comment]
cross fingers

**Comment by IainNZ** [comment]
Safe to tag then?

**Comment by tkelman** [comment]
I doubt it could get any worse? julia.mit.edu is down again so I can't easily test on Linux right now without waiting in a travis queue.

**Comment by tkelman** [comment]
btw thanks again @kbarbary for the responsiveness and (knock on wood) fix here

**Comment by IainNZ** [comment]
I'm happy with that logic. Will tag before midnight EST.

**Comment by kbarbary** [comment]
Sure, sorry for the original hasty change!

**Pull request merged**
