### PR TITLE
Add GSL.jl example and update link to Cairo.jl in README.md

### PR DESCRIPTION
**Pull request by nalimilan**
A simple example is easier to understand for starters.
The link to Cairo.jl pointed to an old branch, better follow master.

### CODE REVIEW

**Comment by nalimilan** [comment]
GSL.jl is the only package I could find with the simple case, and yet support for all platforms, as well as both source and binaries. Other suggestions welcome.

**Comment by tkelman** [comment]
We may want to point to specific tags as opposed to master, since these may change.

**Comment by nalimilan** [comment]
Yes, I wondered about that, but in the end I concluded that we'd better always refer to master. As this PR shows, the links will likely get out of date if we choose specific tags, which would really be awful for documentation purposes. OTC, master should always reflect the current status of BinDeps.

**Comment by tkelman** [comment]
Not if some replacement for BinDeps comes along and those packages start using it?

**Comment by nalimilan** [comment]
Well, yeah, but if this ever happens it will be only once and we can fix it. OTC, smaller changes/improvements to the BinDeps syntax are more likely to be frequent. Giving examples that don't work would be terrible.

**Comment by nalimilan** [comment]
So, final word? :-)

**Pull request merged**
