### PR TITLE
Work around macro needing Compat functions by use of interpolation

### PR DESCRIPTION
**Pull request by musm**
Courtesy  @TotalVerb

I think this is cleaner

### CODE REVIEW

**Comment by tkelman** [comment]
I disagree, this is more complicated.

**Comment by musm** [comment]
lol okay.

**Comment by tkelman** [comment]
Turns out that without this we get a deprecation from 0cbd186679ea88dfd0635bf98c3a724766903d44 on 0.4, so this is worth doing after all even though the interpolation could be a little confusing.

**Comment by tkelman** [comment]
Thanks! Nightly failures are issues in other test-dep packages

**Pull request merged**
