### PR TITLE
Add test status badges

### PR DESCRIPTION
**Pull request by ararslan**
I'd add the AppVeyor badge too but I don't have the URL for it.

### CODE REVIEW

**Comment by tkelman** [comment]
hm, need to fix dict syntax in cairo and tag winrpm for nightly apparently. i think there's a way to construct the appveyor badge link for public repos.

**Comment by ararslan** [comment]
There definitely is for Travis but the AppVeyor URLs have some kind of hash or other garbage in there. Could ask Milan for the link since it runs under his account but it'll be a while.

**Comment by tkelman** [comment]
I think there's a way of doing it that references the github org rather than the appveyor account hash in the badge url (I asked for them to add this capability some time ago). buried in their docs somewhere

**Comment by ararslan** [comment]
Yep, you're absolutely right. Thanks!

**Comment by ararslan** [comment]
Bump

**Pull request merged**
