### PR TITLE
Prepare for using Compat for new tuple syntax

### LINKED ISSUE #141: 0.4 tuple changes prevent BinDeps from loading
caused by https://github.com/JuliaLang/julia/pull/10380
```
  | | |_| | | | (_| |  |  Version 0.4.0-dev+4319 (2015-04-17 03:26 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit ef06211* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> using BinDeps
ERROR: LoadError: LoadError: TypeError: apply_type: in alias, expected Type{T}, got Tuple{DataType,DataType}
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:51
while loading /home/tkelman/.julia/v0.4/BinDeps/src/dependencies.jl, in expression starting on line 16
while loading /home/tkelman/.julia/v0.4/BinDeps/src/BinDeps.jl, in expression starting on line 489
```

### PR DESCRIPTION
**Pull request by tkelman**
depends on https://github.com/JuliaLang/Compat.jl/pull/63, or suitable replacement (once it gets tagged, should bump Compat version in REQUIRE too)

should fix #141

### CODE REVIEW

**Comment by rened** [comment]
LGTM, `Pkg.add("HDF5")` on julia master works on OSX when using this and https://github.com/JuliaLang/Compat.jl/pull/63

**Comment by tkelman** [comment]
Thanks for the testing, much appreciated - I checked `Pkg.build` on ZMQ and Nettle on 0.3 and 0.4, I think these should cover the basics to start with, let people find the remaining trouble spots either through PkgEvaluator or on their own.

**Comment by rened** [comment]
https://github.com/JuliaLang/Compat.jl/pull/63 was just merged, so I believe this is good to go.

**Comment by mlubin** [comment]
Tested this on both 0.3 and 0.4 locally. Seems okay.

**Comment by mlubin** [comment]
Is this ready to tag?

**Comment by tkelman** [comment]
Sorry was offline. Should bump REQUIRE then tag, I'll do it.

**Pull request merged**
