### PR TITLE
Remove old code for check_path!

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by musm** [comment]
Retrigerring ci even though failures are unrelated

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
does this look good?

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
this is removing dead code  (package is for version greater than 0.5)

**Comment by musm** [comment]
cc @ararslan  @tkelman

**Comment by tkelman** [comment]
I watch this package already. You really don't need to repeatedly bump this.

**Pull request merged**
