### PR TITLE
Add BuildProcess to windows providers

### PR DESCRIPTION
**Pull request by musm**
requested addition https://github.com/JuliaLang/BinDeps.jl/issues/55

### CODE REVIEW

**Comment by tkelman** [comment]
This is unlikely to work for most of these that get written, given the usual lack of development tools on windows.

**Comment by musm** [comment]
What I see in practice is custom  unpackaging and installation scripts that are used within in a 
 `is_windows()` branch that end up using  `BuildProcess` , which makes this patch useful

**Comment by musm** [comment]
I  several others have made the same observations. Would be nice to just have it as a default. Instead of having to resort to, which is what is currently necessary,
```
is_windows() && push!(BinDeps.defaults, BuildProcess)
...
is_windows() && pop!(BinDeps.defaults)
```

**Comment by musm** [comment]
As a note the 32-bit cairo failures are unrelated  see https://github.com/JuliaGraphics/Cairo.jl/issues/192

**Comment by tkelman** [comment]
The problem is the default BuildProcess doesn't have an OS conditional. So this would enable all the BuildProcess providers out there that have been written using configure and make that won't work at all. At least having to go to the extra length of adding it manually is a way of certifying yes, you know it should work, as opposed to default assuming it will work cross-platform which will often be a wrong assumption.

**Comment by musm** [comment]
Closing as it seems that you do not want this

**Pull request closed without merging**
